const mongoose = require('mongoose');
const { Schema } = mongoose;

/** One per sign per day — generated by a scheduled job calling Claude (see jobs/generateDailyContent.js). */
const horoscopeSchema = new Schema(
  {
    sign: { type: String, required: true },
    period: { type: String, enum: ['daily', 'weekly'], required: true },
    dateKey: { type: String, required: true }, // 'YYYY-MM-DD' for daily, 'YYYY-WW' for weekly
    content: { type: String, required: true },
  },
  { timestamps: true }
);
horoscopeSchema.index({ sign: 1, period: 1, dateKey: 1 }, { unique: true });

const tarotCardSchema = new Schema(
  {
    name: { type: String, required: true },
    arcana: { type: String, enum: ['major', 'minor'], required: true },
    imageUrl: { type: String, required: true },
    uprightMeaning: { type: String, required: true },
    reversedMeaning: { type: String, required: true },
  },
  { timestamps: true }
);

const dailyTarotDrawSchema = new Schema(
  {
    owner: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    dateKey: { type: String, required: true },
    card: { type: Schema.Types.ObjectId, ref: 'TarotCard', required: true },
    reversed: { type: Boolean, default: false },
    aiInterpretation: { type: String, default: null },
  },
  { timestamps: true }
);
dailyTarotDrawSchema.index({ owner: 1, dateKey: 1 }, { unique: true });

const moonRitualSchema = new Schema(
  {
    phase: { type: String, enum: ['new', 'full'], required: true, index: true },
    title: { type: String, required: true },
    body: { type: String, required: true },
  },
  { timestamps: true }
);

const angelNumberSchema = new Schema(
  {
    number: { type: String, required: true, unique: true, index: true }, // e.g. '1111', '444'
    meaning: { type: String, required: true },
  },
  { timestamps: true }
);

/** Astronomical/astrological calendar events: eclipses, full/new moons, retrograde windows, solstices. */
const calendarEventSchema = new Schema(
  {
    title: { type: String, required: true },
    type: {
      type: String,
      enum: ['eclipse', 'full_moon', 'new_moon', 'retrograde_start', 'retrograde_end', 'solstice', 'equinox'],
      required: true,
    },
    date: { type: Date, required: true, index: true },
    endDate: { type: Date, default: null }, // used for retrograde windows (start -> end)
    planet: { type: String, default: null }, // relevant for retrograde events
    description: { type: String, default: '' },
    energyRating: { type: String, enum: ['green', 'amber', 'red'], default: 'green' }, // day-energy dot color
  },
  { timestamps: true }
);
calendarEventSchema.index({ date: 1, type: 1 });

module.exports = {
  Horoscope: mongoose.model('Horoscope', horoscopeSchema),
  TarotCard: mongoose.model('TarotCard', tarotCardSchema),
  DailyTarotDraw: mongoose.model('DailyTarotDraw', dailyTarotDrawSchema),
  MoonRitual: mongoose.model('MoonRitual', moonRitualSchema),
  AngelNumber: mongoose.model('AngelNumber', angelNumberSchema),
  CalendarEvent: mongoose.model('CalendarEvent', calendarEventSchema),
};
